---
title: "Minimal Example of Tutorial as R package vignette"
author:
- Raniere Silva
bibliography: references.bib
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This example demonstrates the required metadata by [`methodshub`](https://github.com/GESIS-Methods-Hub/methodshub).

## Markdown {#sec-markdown}

::: {.callout-important}

[`methodshub`](https://github.com/GESIS-Methods-Hub/methodshub) uses [Quarto](https://quarto.org/) and [`pkgdown`](https://pkgdown.r-lib.org/) uses [R Markdown](https://rmarkdown.rstudio.com/) to convert Markdown to HTML.

:::

R Markdown does **not** support cross-references like @sec-markdown.

R Markdown supports code execution [@xie2018r].

## Execution of R code

```{r}
1 + 1
```

## Execution of R code from package

```{r setup}
library(mwe)
```

```{r}
hello()
```

## Creation of figure with R

```{r}
plot(rnorm(10), rnorm(10))
```

### References

::: {#refs}
:::
